services:
  api:
    build:
      context: .
      dockerfile: backend_api/Dockerfile
    container_name: paperlessboss_api
    restart: always
    env_file:
      - .env
    networks:
      - production-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: paperlessboss_nginx
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      # Mount host Let's Encrypt certificates directly into the Nginx container
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    networks:
      - production-network
    depends_on:
      - api

networks:
  production-network:
    driver: bridge
